### ISSUE TITLE
Комментарий к заявке

### ISSUE THREAD

**Issue by aakuptsov** [bty448/ivr_project_request#1]
1. К защите не допускаются приложения справочного характера, то есть, такие, которые представляют собой, по сути, оцифрованные учебники и т. п. 

В данном проекте нужно больше интерактива. 

2. >>Полное собрание произведений, содержащихся в школьной программе литературы

Могу ошибаться, но не все из них находятся в public domain и проблему авторских прав нужно учитывать.

**Comment by bty448** [comment]
> 
> 
>     1. К защите не допускаются приложения справочного характера, то есть, такие, которые представляют собой, по сути, оцифрованные учебники и т. п.
> 
> 
> В данном проекте нужно больше интерактива.
> 
>     1. > > Полное собрание произведений, содержащихся в школьной программе литературы
> 
> 
> Могу ошибаться, но не все из них находятся в public domain и проблему авторских прав нужно учитывать.

1) В качестве интерактива в проекте выступают небольшие тесты для самопроверки после прочтения пользователем произведения. Помимо этого, я могу добавить возможность делать пользовательские комментарии прямо в тексте проиизведения (они будут выделяться) и, как вариант, возможность задания ключевых названий этим комментариям и быстрый переход к месту в тексте, где они содержится.

2) Я нагуглил, что авторское право на произведение пропадает через 70 лет после смерти автора. Присутствие произведений писателей, умерших позже 1948 года, входящих в школьный курс литературы я буду выделять особым образом: кнопка с произведением будет неактивна, но при касании этой кнопки пользователем будет высвечиваться сообщение о том, что произведение было невозможно добавить в приложение в связи с авторским правом. Таких произведений в школьном курсе очень мало, поэтому такое решение проблемы не должно быть сильно неудобным для пользователя. Авторское право на краткие содержания произведений с briefly.ru есть, поэтому я решил не добавлять этот функционал в программу.

**Comment by bty448** [comment]
Спасибо за отличную идею! Обязательно добавлю такую возможность.

**Comment by aakuptsov** [comment]
Я поставлю зачёт, но предлагаю перезаявить проект как образовательный.
